export enum LeaveType {
    EARNED = "EARNED",
    CASUAL = "CASUAL",
    MEDICAL = "MEDICAL",
    EXTRAWITHPAY = "EXTRAWITHPAY",
    EXTRAWITHOUTPAY = "EXTRAWITHOUTPAY",
    MATERNITY = "MATERNITY",
    PATERNITY = "PATERNITY",
    STUDY = "STUDY",
    SPECIAL_DISABILITY = "SPECIAL_DISABILITY",
    QUARANTINE = "QUARANTINE",
    SPECIAL = "SPECIAL",
}

export enum Role {
    EMPLOYEE = "EMPLOYEE",
    DEPT_HEAD = "DEPT_HEAD",
    HR_ADMIN = "HR_ADMIN",
    HR_HEAD = "HR_HEAD",
    CEO = "CEO",
    SYSTEM_ADMIN = "SYSTEM_ADMIN",
}

export enum LeaveStatus {
    DRAFT = "DRAFT",
    SUBMITTED = "SUBMITTED",
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    CANCELLED = "CANCELLED",
    RETURNED = "RETURNED",
    CANCELLATION_REQUESTED = "CANCELLATION_REQUESTED",
    RECALLED = "RECALLED",
}

export enum EncashmentStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    PAID = "PAID",
}
