-- CreateEnum for NotificationType
CREATE TYPE "NotificationType" AS ENUM (
  'LEAVE_SUBMITTED',
  'LEAVE_APPROVED',
  'LEAVE_REJECTED',
  'LEAVE_RETURNED',
  'LEAVE_FORWARDED',
  'LEAVE_CANCELLED',
  'LEAVE_CANCELLATION_REQUESTED',
  'LEAVE_APPROACHING',
  'APPROVAL_REQUIRED',
  'ENCASHMENT_APPROVED',
  'ENCASHMENT_REJECTED',
  'SYSTEM_ANNOUNCEMENT'
);

-- CreateTable Notification
CREATE TABLE `Notification` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `userId` INTEGER NOT NULL,
  `type` ENUM('LEAVE_SUBMITTED', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LEAVE_RETURNED', 'LEAVE_FORWARDED', 'LEAVE_CANCELLED', 'LEAVE_CANCELLATION_REQUESTED', 'LEAVE_APPROACHING', 'APPROVAL_REQUIRED', 'ENCASHMENT_APPROVED', 'ENCASHMENT_REJECTED', 'SYSTEM_ANNOUNCEMENT') NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `link` VARCHAR(191) NULL,
  `leaveId` INTEGER NULL,
  `read` BOOLEAN NOT NULL DEFAULT false,
  `readAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expiresAt` DATETIME(3) NULL,

  INDEX `Notification_userId_read_idx`(`userId`, `read`),
  INDEX `Notification_userId_createdAt_idx`(`userId`, `createdAt`),
  INDEX `Notification_createdAt_idx`(`createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
